// <auto-generated />
using System;
using Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(StandardContest2023Context))]
    [Migration("20240829090446_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Contest", b =>
                {
                    b.Property<int>("ContestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContestID"), 1L, 1);

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("AppSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContestUniqueCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionContest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryExclusionFields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvalidSmsresponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvalidWhatsappResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissingFieldResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameContest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepeatedOnlinePageResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepeatedSmsresponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepeatedWhatsappResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidOnlineCompletionResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidOnlinePageResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidSmsresponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidWhatsappResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WinnerExclusionFields")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContestID");

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("Entities.Models.ContestFieldDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ContestID")
                        .HasColumnType("int");

                    b.Property<int>("FieldID")
                        .HasColumnType("int");

                    b.Property<string>("FieldLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsOnlineCompletion")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOnlinePage")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("RegexID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegexValidationID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ContestID");

                    b.HasIndex("FieldID");

                    b.HasIndex("RegexValidationID");

                    b.ToTable("ContestFieldDetails");
                });

            modelBuilder.Entity("Entities.Models.ContestFields", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ContestFields");
                });

            modelBuilder.Entity("Entities.Models.RegexValidation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RegexValidations");
                });

            modelBuilder.Entity("Entities.Models.ContestFieldDetails", b =>
                {
                    b.HasOne("Entities.Models.Contest", "Contest")
                        .WithMany("ContestFieldDetails")
                        .HasForeignKey("ContestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.ContestFields", "Field")
                        .WithMany("ContestFieldDetails")
                        .HasForeignKey("FieldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.RegexValidation", "RegexValidation")
                        .WithMany("ContestFieldDetails")
                        .HasForeignKey("RegexValidationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("Field");

                    b.Navigation("RegexValidation");
                });

            modelBuilder.Entity("Entities.Models.Contest", b =>
                {
                    b.Navigation("ContestFieldDetails");
                });

            modelBuilder.Entity("Entities.Models.ContestFields", b =>
                {
                    b.Navigation("ContestFieldDetails");
                });

            modelBuilder.Entity("Entities.Models.RegexValidation", b =>
                {
                    b.Navigation("ContestFieldDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
